"""add parameters columns to strategy table

Revision ID: 0afa2815a3d7
Revises: 0b52e8df1178
Create Date: 2024-06-26 09:24:54.764918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0afa2815a3d7'
down_revision: Union[str, None] = '0b52e8df1178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_strategy', sa.Column('Parameters', sa.JSON(), nullable=True))
    op.drop_column('dim_strategy', 'IndicatorParameterNames')
    op.drop_column('dim_strategy', 'Indicator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_strategy', sa.Column('Indicator', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('dim_strategy', sa.Column('IndicatorParameterNames', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('dim_strategy', 'Parameters')
    # ### end Alembic commands ###
