"""rename add cash and commission columns

Revision ID: 0b52e8df1178
Revises: de27d2ebc480
Create Date: 2024-06-25 22:12:10.197415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b52e8df1178'
down_revision: Union[str, None] = 'de27d2ebc480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
