"""add first_name and last_name columns to user

Revision ID: 11ac80d5acb0
Revises: 7db4e7dcd94f
Create Date: 2024-06-27 09:41:23.723463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ac80d5acb0'
down_revision: Union[str, None] = '7db4e7dcd94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dim_strategy', 'StrategyName',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('dim_users', sa.Column('FirstName', sa.String(length=100), nullable=True))
    op.add_column('dim_users', sa.Column('LastName', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_users', 'LastName')
    op.drop_column('dim_users', 'FirstName')
    op.alter_column('dim_strategy', 'StrategyName',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
