"""add DateKey to trades table

Revision ID: 14bd3255402b
Revises: 5c93e85e8c7d
Create Date: 2024-06-25 15:27:07.546629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14bd3255402b'
down_revision: Union[str, None] = '5c93e85e8c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_trades', sa.Column('DateKey', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fact_trades', 'dim_date', ['DateKey'], ['DateKey'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_trades', type_='foreignkey')
    op.drop_column('fact_trades', 'DateKey')
    # ### end Alembic commands ###
