"""change currenttime to createdAt in backtests

Revision ID: 1a878c24a969
Revises: 108f8251fa0b
Create Date: 2024-06-25 15:36:00.728712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a878c24a969'
down_revision: Union[str, None] = '108f8251fa0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_backtests', sa.Column('CreatedAt', sa.DateTime(), nullable=True))
    op.drop_column('fact_backtests', 'CurrentTime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_backtests', sa.Column('CurrentTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('fact_backtests', 'CreatedAt')
    # ### end Alembic commands ###
