"""add column strategy identifier

Revision ID: 385ed44b1e0c
Revises: b123e8923db6
Create Date: 2024-06-25 16:17:53.246762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385ed44b1e0c'
down_revision: Union[str, None] = 'b123e8923db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_strategy', sa.Column('StrategyIdentifier', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_strategy', 'StrategyIdentifier')
    # ### end Alembic commands ###
