"""Add indicator info columns in Strategy table

Revision ID: 7e99921c973a
Revises: 9c09f2373cf5
Create Date: 2024-06-25 14:27:24.345832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e99921c973a'
down_revision: Union[str, None] = '9c09f2373cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_strategy', sa.Column('Indicator', sa.String(length=100), nullable=True))
    op.add_column('dim_strategy', sa.Column('IndicatorParameterNames', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_strategy', 'IndicatorParameterNames')
    op.drop_column('dim_strategy', 'Indicator')
    # ### end Alembic commands ###
