"""remove relationship - Dim_Strategy.backtests

Revision ID: b123e8923db6
Revises: 0102ff341fb3
Create Date: 2024-06-25 16:03:58.032087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b123e8923db6'
down_revision: Union[str, None] = '0102ff341fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_backtests', sa.Column('Scene_ID', sa.Integer(), nullable=True))
    op.drop_constraint('fact_backtests_StrategyID_fkey', 'fact_backtests', type_='foreignkey')
    op.create_foreign_key(None, 'fact_backtests', 'dim_scene', ['Scene_ID'], ['SceneID'])
    op.drop_column('fact_backtests', 'StrategyID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_backtests', sa.Column('StrategyID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fact_backtests', type_='foreignkey')
    op.create_foreign_key('fact_backtests_StrategyID_fkey', 'fact_backtests', 'dim_strategy', ['StrategyID'], ['StrategyID'])
    op.drop_column('fact_backtests', 'Scene_ID')
    # ### end Alembic commands ###
