"""Change parameters to parametersnames

Revision ID: d737ef9ba8e5
Revises: 0afa2815a3d7
Create Date: 2024-06-26 09:26:05.850371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd737ef9ba8e5'
down_revision: Union[str, None] = '0afa2815a3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_strategy', sa.Column('ParametersNames', sa.JSON(), nullable=True))
    op.drop_column('dim_strategy', 'Parameters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_strategy', sa.Column('Parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('dim_strategy', 'ParametersNames')
    # ### end Alembic commands ###
