"""rename add cash and commission columns

Revision ID: de27d2ebc480
Revises: 58cdc5f2d9f3
Create Date: 2024-06-25 22:10:08.259427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de27d2ebc480'
down_revision: Union[str, None] = '58cdc5f2d9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_scene', sa.Column('Cash', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('dim_scene', sa.Column('Commission', sa.Numeric(precision=18, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_scene', 'Commission')
    op.drop_column('dim_scene', 'Cash')
    # ### end Alembic commands ###
