"""Change TotalReturn to Return in backtest results

Revision ID: e36456dd84e4
Revises: 7e99921c973a
Create Date: 2024-06-25 14:51:34.029979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36456dd84e4'
down_revision: Union[str, None] = '7e99921c973a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_backtests', sa.Column('Return', sa.Numeric(precision=18, scale=4), nullable=True))
    op.drop_column('fact_backtests', 'TotalReturn')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_backtests', sa.Column('TotalReturn', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True))
    op.drop_column('fact_backtests', 'Return')
    # ### end Alembic commands ###
